Language: english
Version-check: true
Prefix: none
Zombie:
  OnlyZombies: true
  Speed: 15
  Smoothness: 5
  AttackStrength: 4
  Health: 12
  PickUpPlayerArmor: true
Thirst:
  Speed: 2
Chest:
  IfOnlyEmpty: true
  RegenTime: 2
  Disappear: true
WandItem: 369
ControlSItems: true
ColouredTags: true
EnableRegions: false
MySQL:
  Username: root
  Password: root
  Hostname: localhost
  Port: 3306
  Database: darkdays
  DataWrapper: none
