Language: english
Version-check: true
Prefix: DarkDays
DisableHealthRegen: false
WandItem: 369
ControlSItems: true
ColouredTags: true
EnableRegions: false
SpawnWithBlindness: true
Zombie:
  Speed: 12
  Smoothness: 5
  AttackStrength: 4
  Health: 24
  PickUpPlayerArmor: true
Thirst:
  Speed: 2
Chest:
  IfOnlyEmpty: true
  RegenTime: 2
  Disappear: true
  ClickToDestroy: true
MySQL:
  Username: root
  Password: root
  Hostname: localhost
  Port: 3306
  Database: darkdays
  DataWrapper: none
Noise:
  EnableBlockData: true
  Multiplier: 0.3
  L1: 1,2,3
  L2: 4,5,6