name: DarkDays
main: darvin939.DarkDays.DarkDays
version: 0.94
description: DarkDays Mod v0.94
author: darvin939, darvin212@gmail.com
softdepend: [TagAPI, StackableItems, SQLibrary]
commands:
  dd:
    usage: /dd help
    description: Show help topic